"""Compatibility layer for training configuration imports.

This module exposes the training-step settings explicitly so callers do not
depend on wildcard re-exports.
"""

from .symbols import SYMBOLS as TRAINING_SYMBOLS
from .training_step import (
	Manual,
	TRAINING_BENCHMARK_SYMBOL,
	TRAINING_ITERATIONS,
	TRAINING_LOG_FILENAME,
	TRAINING_MANUAL_PENGUINS,
	TRAINING_PARAMETER_DELTA_FILENAME,
	TRAINING_PARAMETER_LOG_FILENAME,
	TRAINING_PENGUINS,
	TRAINING_RANDOM_SEED,
	TRAINING_RESULTS_FILENAME,
	TRAINING_STEP_ENABLED,
	TRAINING_SUBSET_MONTHS,
	TRAINING_SUBSET_STOCKS,
	TRAINING_TRANSACTION_COST,
)

__all__ = [
	"TRAINING_SYMBOLS",
	"TRAINING_STEP_ENABLED",
	"TRAINING_ITERATIONS",
	"TRAINING_SUBSET_MONTHS",
	"TRAINING_SUBSET_STOCKS",
	"TRAINING_TRANSACTION_COST",
	"TRAINING_BENCHMARK_SYMBOL",
	"TRAINING_RANDOM_SEED",
	"Manual",
	"TRAINING_PENGUINS",
	"TRAINING_MANUAL_PENGUINS",
	"TRAINING_PARAMETER_DELTA_FILENAME",
	"TRAINING_RESULTS_FILENAME",
	"TRAINING_LOG_FILENAME",
	"TRAINING_PARAMETER_LOG_FILENAME",
]